In [10]:
import math
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv("test_scores.csv")
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [12]:
x = np.array(df.math)
y = np.array(df.cs)

In [13]:
x

array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67])

In [14]:
y

array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73])

In [37]:
def gradientDescent(x,y, learningRate):
    m = b = 0
    i = 1
    n = len(x)
    yPredicted = m * x + b
    prevCost = (1/n)*sum([val**2 for val in (y-yPredicted)])
    mDer = -(2/n)*sum(x*(y-yPredicted))
    bDer = -(2/n)*sum((y-yPredicted))
    m = m - learningRate * mDer
    b = b - learningRate * bDer
    #print(f"m = {m}, b = {b}, iteration = {i}, cost = {prevCost}")
    
    
    
    yPredicted = m * x + b
    cost = (1/n)*sum([val**2 for val in (y-yPredicted)])
    mDer = -(2/n)*sum(x*(y-yPredicted))
    bDer = -(2/n)*sum((y-yPredicted))
    m = m - learningRate * mDer
    b = b - learningRate * bDer
    
    
    
    #print(f"m = {m}, b = {b}, iteration = {i}, cost = {cost}")
    while(not(math.isclose(prevCost,cost,rel_tol=1e-20))):
        yPredicted = m * x + b
        prevCost = cost
        cost = (1/n)*sum([val**2 for val in (y-yPredicted)])
        mDer = -(2/n)*sum(x*(y-yPredicted))
        bDer = -(2/n)*sum((y-yPredicted))
        m = m - learningRate * mDer
        b = b - learningRate * bDer
        i+=1
        
    print(f"m = {m}, b = {b}, iteration = {i}, cost = {cost}")
        

In [41]:
gradientDescent(x,y,0.0001)

m = 1.0177392018821385, b = 1.9150092583843652, iteration = 793646, cost = 31.604511336062526


In [ ]:
#m = 1.0444490635018007, b = 0.014950923273574925, iteration = 975540, cost = 31.81185409244676

In [42]:
from sklearn.linear_model import LinearRegression

In [48]:
reg = LinearRegression()
x = np.reshape(x, (-1, 1))
y = np.reshape(y, (-1, 1))

In [49]:
reg.fit(x,y)

LinearRegression()

In [50]:
reg.coef_

array([[1.01773624]])

In [51]:
reg.intercept_

array([1.91521931])